version: "3.8"

services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lleoW7jg6zzGYpbbf228
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5654:5432"
volumes:
  postgres:
